# Generated by Django 5.1.6 on 2025-02-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file_path',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
